# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'snake_game.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(827, 630)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 50, 751, 461))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.startButton = QtWidgets.QPushButton(self.layoutWidget)
        self.startButton.setObjectName("startButton")
        self.gridLayout.addWidget(self.startButton, 2, 1, 1, 1)
        self.playerName = QtWidgets.QLineEdit(self.layoutWidget)
        self.playerName.setObjectName("playerName")
        self.gridLayout.addWidget(self.playerName, 0, 0, 1, 1)
        self.leaderboardList = QtWidgets.QListWidget(self.layoutWidget)
        self.leaderboardList.setObjectName("leaderboardList")
        self.gridLayout.addWidget(self.leaderboardList, 1, 5, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.layoutWidget)
        self.graphicsView.setStyleSheet("background-colour: rgb(85, 0, 127)")
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 1, 0, 1, 4)
        self.scoreLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.scoreLabel.setFont(font)
        self.scoreLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.scoreLabel.setObjectName("scoreLabel")
        self.gridLayout.addWidget(self.scoreLabel, 0, 3, 1, 1)
        self.topscores = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.topscores.setFont(font)
        self.topscores.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.topscores.setObjectName("topscores")
        self.gridLayout.addWidget(self.topscores, 0, 5, 1, 1)
        self.RestartGame = QtWidgets.QPushButton(self.layoutWidget)
        self.RestartGame.setObjectName("RestartGame")
        self.gridLayout.addWidget(self.RestartGame, 2, 2, 1, 1)
        self.Quit = QtWidgets.QPushButton(self.layoutWidget)
        self.Quit.setObjectName("Quit")
        self.gridLayout.addWidget(self.Quit, 2, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.leaderboardList.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Snake Game"))
        self.startButton.setText(_translate("MainWindow", "start Game"))
        self.playerName.setPlaceholderText(_translate("MainWindow", "Enter your name"))
        self.leaderboardList.setSortingEnabled(True)
        self.scoreLabel.setText(_translate("MainWindow", "SNAKE GAME"))
        self.topscores.setText(_translate("MainWindow", " Top Scores"))
        self.RestartGame.setText(_translate("MainWindow", "Restart Game"))
        self.Quit.setText(_translate("MainWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
